#!/bin/sh

if [ -e "$HOME"/.local/share/nvim/site/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim -u "$HOME"/.config/nvim/lua/bundles.lua +PlugUpdate +PlugClean! +qa

reset -Q
