#!/bin/bash

if [ -e "$HOME"/.local/share/nvim/site/autoload/plug.vim ]; then
  nvim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim -u "$HOME"/.config/nvim/lua/bundles.lua +PlugUpdate +PlugClean! +qa

# For some reason, the lua script for telescope does
# not properly run make so we do it manually here.
cd $HOME/.config/nvim/plugged/telescope-fzf-native.nvim
make &>/dev/null
cd $HOME/dotfiles
